### ISSUE TITLE
Installation fails: ImportError: No module named django_tablib

### ISSUE THREAD

**Issue by chriswayg** [divio/django-cms-demo#47]
I cannot successfully install django-cms-demo on Debian 7 due to ImportError: No module named django_tablib

```
[django-cms-demo]# make install
...
Successfully installed aldryn-jobs-1.0.1
source env/bin/activate; npm install
make migrate
make[2]: Entering directory `/opt/docker/compose/django-cms-demo'
source env/bin/activate; env/bin/python src/manage.py migrate --noinput
Traceback (most recent call last):
  File "src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/docker/compose/django-cms-demo/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/opt/docker/compose/django-cms-demo/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/opt/docker/compose/django-cms-demo/env/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/docker/compose/django-cms-demo/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/opt/docker/compose/django-cms-demo/env/local/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django_tablib
make[2]: *** [migrate] Error 1
```

how to get it to install?

Christian

**Comment by FinalAngel** [comment]
sorry for the late answer @chriswayg . You basically would have to add ``django-tablib`` to the requirements but we have fixed this issue in the latest master :)
