### ISSUE TITLE
Running make docker on Mac OSX fails.

### ISSUE THREAD

**Issue by spud93** [divio/django-cms-demo#82]
Starting djangocmsdemo_data_1
/usr/local/lib/python2.7/site-packages/reversion/models.py:6: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

/usr/local/lib/python2.7/site-packages/aldryn_jobs/models.py:18: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/usr/local/lib/python2.7/site-packages/aldryn_locations/models.py", line 21, in <module>
    MARKER_CONTENT_FORMAT = unicode(settings.ALDRYN_LOCATIONS_MARKER_CONTENT_FORMAT)
  File "/usr/local/lib/python2.7/site-packages/django/conf/**init**.py", line 49, in **getattr**
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'ALDRYN_LOCATIONS_MARKER_CONTENT_FORMAT'
make[1]: **\* [docker_database] Error 1
make: **\* [docker] Error 2

**Comment by austinjung** [comment]
Hi, did you solve the issue?
I also have the same issue. Please let me know if you solve this.

Thanks.

**Comment by tkuther** [comment]
Exact same thing on Linux, so it's not host specific.

**Comment by FinalAngel** [comment]
fixes have been pushed with additional information to master 👍
